### ISSUE TITLE
In-Game Menu Decision

### ISSUE THREAD

**Issue by JY-H** [Kimchelly/Project-Blob#13]
Kim, 

I asked around and apparently there's no way to pause game, switch scene (jump to options scene) and return to where you were in the game. So I don't know what you want to do with this. 

An in game panel? Switch scenes anyway? (probably with popup telling you that your progress will be lost).

**Comment by Kimchelly** [comment]
It's not really as important to switch over to an options menu unless you're in the main menu so I suppose it's not that important. All we really need is a game pause overlay with a "Resume" option and a "Quit" option.. For the pausing, I'll write something to pause all the components in the scene. The resume will just stop the pausing and the quit will just exit to the main menu.

**Comment by JY-H** [comment]
@Kimchelly Works for me.
