### ISSUE TITLE
Game music toggle doesn't work as intended

### ISSUE THREAD

**Issue by Kimchelly** [Kimchelly/Project-Blob#14]
There's a problem with the ToggleMusic() function in OptionsMenu.cs (and presumably BackgroundMusicSingleton.cs as well) where the settings are saved correctly (it remembers if the music was toggle on/off) but if you start the menu scene, go to options, turn off music, reload the menu (music is still toggled off), and go to options, it throws a NullReference exception.

NullReferenceException: Object reference not set to an instance of an object
OptionsMenu.ToggleMusic () (at Assets/Scripts/OptionsMenu.cs:48)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:110)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:574)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:716)
UnityEngine.Events.UnityEvent`1[System.Boolean].Invoke (Boolean arg0) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_1.cs:53)
UnityEngine.UI.Toggle.Set (Boolean value, Boolean sendCallback) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Toggle.cs:167)
UnityEngine.UI.Toggle.Set (Boolean value) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Toggle.cs:142)
UnityEngine.UI.Toggle.set_isOn (Boolean value) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Toggle.cs:136)
OptionsMenu.Awake () (at Assets/Scripts/OptionsMenu.cs:26)

**Comment by Kimchelly** [comment]
Also the OptionsMenu script just turns itself off if I turn off music/effects.
... Also the text for sound, music, and effects on the options menu are overlayed on top of each other.
Actually now that I play with it, it throws NullReferenceExceptions if:
1. Music or sfx is turned off and the main menu is reloaded.
2. You try toggling music or sfx after reload.
![image](https://cloud.githubusercontent.com/assets/8785663/8112648/3481f6ac-1037-11e5-8ee2-e12a81868b5e.png)

**Comment by Kimchelly** [comment]
Good luck boi

**Comment by JY-H** [comment]
Alright it's now fixed. 

Was an issue of assignment a static modifier to a Singleton instance. Should work now.
