### ISSUE TITLE
Combat System

### ISSUE THREAD

**Issue by Kimchelly** [Kimchelly/Project-Blob#18]
So the gigantic unanswered question of how we're going to make combat. I already started with the player and enemy simple projectile firing system (just fire some fireball at the other person and do damage). If we're going to have melee and more long-ranged weapons, we probably have to be kind of creative with it. So just list a rough idea of some random things you might like to see in a combat system, ex: weapons, maneuvers, special attacks, ranges, etc.
Add whatever weapons you might like to see.

* Sword attack (short range): basic slash with a sword, maybe make some kind of combos (although it's complicated, it would probably be doable if we had graphics to accompany it).
* Bow and arrow (long range): shoot arrows, ammo system, get more arrows by killing enemies or something and they randomly drop more.
* Magic (short/long range): completely up to creativity and graphics how it will work.
* Pets: I've been thinking a while about the idea of having familiars/other characters you can switch out to. This would also be complex 
    * We could add an option in the pause menu for items, switching out characters, equipping weapons, etc. This would be much further in development but a possibility for switching weapons.

**Comment by JY-H** [comment]
* Okay, in terms of the combat system, I think right now it might be easiest to do the bow and arrow thing. (We don't even need the bow animation!). Just fire a projectile-like thing upon key press or something. 
* Let's include magic later on. 
* Pets sounds pretty good. I can work on the menu option for that. Also been looking for an effective way to do in game menus though not with much luck. I will let you know when I think my UI skills are okay with building that inventory system and stuff. lela. 

Also, did you check my last merge? Is the option menu functioning properly now? (It should be, but let me know if it doesn't).
