### ISSUE TITLE
Saving and saving the location (scene) you're in

### ISSUE THREAD

**Issue by Kimchelly** [Kimchelly/Project-Blob#24]
We need:
1. Savepoints within a scene, like a halfway checkpoint/right before a boss.
2. Saves between scene changes - ex: going from one part of a level through a teleporter, door, etc. to the next scene in the. Note: this will require you to change a few lines of code in menu.unity where
`Application.LoadLevel(string sceneName)` occurs so that you first get `Playerprefs.GetString("currentScent")` (something like that) and load that level. I'll handle loading the player position.
I'll handle these (hopefully) by the end of today and then tell you how to change the MenuNavigator to handle the current saved scene.

**Comment by JY-H** [comment]
I would prefer if it's scene changes, that way I can easily save the progress. Although that will require you to make the Player a singleton.
